export const iconNames = [
  'chart',
  'home',
  'refferal',
  'setting',
  'subscription',
  'wallet',
  'arrow-right',
  'calculator',
  'copy',
  'exit',
  'export',
  'fail',
  'filter',
  'googlePlay',
  'history',
  'instagram',
  'money',
  'payment',
  'plus',
  'refferal-code',
  'refresh',
  'telegram',
  'tick',
  'appStore',
  'eye',
  'eye-blocked',
  'chevron-left',
  'logo',
  'menu',
  'google',
] as const
export type IconType = (typeof iconNames)[number]
